name: simple_email_moderator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  flutter_riverpod: ^2.6.1
  googleapis: ^14.0.0
  google_sign_in: ^6.2.2
  go_router: ^16.0.0
  hive_flutter: ^1.1.0
  http: ^1.4.0
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner:
  go_router_builder:
  hive_generator:
  riverpod_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/
